Repository githubschool/winter-chill, pull requests merged in 2019-01, with the labels that each got.

#16 Update 0000-01-08-sbvnaveen.md
  _posts/0000-01-08-sbvnaveen.md
Labels: help wanted

#14 Edit caption to fit image
  _posts/0000-01-09-mcranford.md
Labels: Failing Query

#10 Update caption line
  _posts/0000-01-17-graulm.md
Labels: Failing Query

#7 temperature in dc
  _posts/0000-01-02-GeorgeEatsData2018.md
Labels: Weather
